### ISSUE TITLE
Hi Geek

### ISSUE THREAD

**Issue by xlovinglyx** [pgpgeek/thunderbird-addon-eml-editor#3]
I like your 1) Done
& your 2) ;)

& when i look at the code it feels like total gibberish to me,
i wish i had your brain ahaha ))

You've told me you had implemented attachment saving feature But..
added: "there might be some bugs", so for me, as long as you know what
type of bugs i might go through, i can't officially use it before you're certain
those bugs you believe that could happen aren't fixed. I cannot have an image
in its data affected & save it like that with alteration of that image & tell myself
it's ok, it's just a "bug", you know ? ))

So please make sure no bug would arrive before confirming it's updated again.
As with your previous mention, v1.3 remains a beta.

Can you make thunderbird recognize and open eml files from windows folders ?
& not from a thunderbird button.. just like what x-unsent addon by lieser does ?

So next time i have an issue, i won't kill myself spending days trying to obtain updates
that never happen, & i'm sure one person can help and not 2 people with 2 different addons.
Cause Lieser hasn't helped in 10 years & he's now proved me again, he prefers ignoring
my requests instead of adding fixes.

for x-unsent support, he's just updated his addon to a webextension, & he's also told me
he could add X-Priority by a workaround but he didn't do it nor shared a way to do it with you
as i've requested to him.

If you think it's too complicated to make your addon open emls from windows folders directly &
not tb's button. i'll be compelled to use both addons then.

Please make sure there could be no bugs in saving attachments in terms of data-integrity.
& try to find a workaround for X-Priority, otherwise, i end up doing what i've done since
years, opening saved emls with a text editor & go place the string myself all the time,
& this drives "one" nuts. I've been doing this since a decade.

As i've told you, i'll paypal you 20 euros, once it's finished. & as i've told you too,
it might be nothing for you, it's just a gesture, but, for me being on gov's help
& jobless, it's still money. with 20 euros, i buy 20 liters of orange juice, when
i do trash cans to eat ((

**Comment by pgpgeek** [comment]
No need money, i made this for fun ;)
You can drink your orange juice ;)

I've made some fix this morning on the editor & viewer, i'm sûr it's now more stable.
Release : 1.4

**Testing :**
Each test was done with saving & opening step.
I've test this with : 
- no file
- single file
- multiple same files
- multiple differents types of files



**About :**
`Can you make thunderbird recognize and open eml files from windows folders ?
& not from a thunderbird button.. just like what x-unsent addon by lieser does ?`

It's like the "priority" of mail, not  available currently on the webextension api (at my knowledge), if that change, i will apply this ;)

**Comment by xlovinglyx** [comment]
I'll still help once all's fixed, as you're helping, afterall, money has its purpose & is used to be spent.
for attachments, it sounds great enough, as long as the quality of images aren't affected, it's all that
matters afterall, principally.
Concerning the opening of emails from windows folders, couldn't you use lieser's technique ?
& implement addons.thunderbird.net/en-US/thunderbird/addon/x-unsent-support/
in your eml-editor ? i feel much better with you continuing the maintenance of the addon
for caring about my wishes. Afterall, lieser's not the only one to have thought about his
coding approach. it'll feel more secure, cause after more than 10 years of maintenance of
x-unsent support addon, he never managed to add 2 major functions & almost told us
he didn't know if he was going to make of his extension a webextension, & if i loose one
of those addons in the future, i'll be lost ((

& last question, you think the availability of X-Priority in the webextension api, 
is in mozilla's "todo" list already ? or can it be requested from them ?

thanks

**Comment by xlovinglyx** [comment]
1.4 tested, i found an issue:

i saved a photo inline
& another photo attached & an eml file attached.

reopened the saved eml &:

1) the inline image is fine.
2) all the attachments have a problem: they are recognized as *.tmp files,
while anyone should be able to open each files in attachments field as their original name & extension.

**Comment by xlovinglyx** [comment]
& nothing important but would look better: 

In your addon, changing all "ELM" strings to "EML" & in addons.thunderbird.net too if edition's possible & it doesn't take you to recreate the addon page. the url string, the name on page & description.

**Comment by pgpgeek** [comment]
I've fixed the problem about the filename of attachements _(there is no problem of corruption file, it's only about the filename ... but i understand the inconvenience)_. It's the getFile operation provided by the WebExtension API, sometimes the filename isn't good, i've take an other way to get always the real filename.

About the ELM > EML, it's only on the filename of the plugin, a mistake on the initial creation ... it's now corrected.

You will get the changements on the **1.6 version**

**Comment by xlovinglyx** [comment]
what about the opening of files with liesers approach? tell me if u can, thx

**Comment by xlovinglyx** [comment]
I don't know what you've fixed, i restarted, installed v1.6, attacjed a pic & eml & saved it, reopened the eml & tried to open attachments still showing *.tmp files to open in any choosen program & not the exact filename & type of attached files. take your time if necessary, cause, it's not fixed on my side yet.

**Comment by pgpgeek** [comment]
Could you please provide me the filename of your files ? 
Or in the best case, try with some no importants files => if the problem is still here, upload files here.

**Comment by pgpgeek** [comment]
On my side, i've test this worflow without any problem:

1. Create new email, with dest, subject & body.
2. Attach 2 pictures (Jpeg) on the email.
3. Save this email with "Save EML" button as "test1.eml".

**4. Open "test1.eml" and his attachemnts > it's ok, mail is correctly displayed & attachements isn't corrupted with their real filenames.**

5. Create a new email (again with dest, subject & body).
6. Attach on this email the "test1.eml" and 1 picture files.
7. Save this email with "Save EML" button as "test2.eml".

**8. Open "test2.eml" and his attachemnts > it's ok, mail is correctly displayed & attachements isn't corrupted with their real filenames.**

**Comment by xlovinglyx** [comment]
You keep ignoring my question concerning the implementation of liesers code in your addon 
to open emails from the desktop. here's another issue:

1) It's needless to send you files, i tried different files, differently named too, with same result
2) because i have x-unsent support addon "active", there's a conflict & your saved attachments
are all reopened as nsmail-1.tmp or nsmail-2.tmp etc. because the x-unsent tag is needed & you
haven't implemented using lieser's code. but without lieser's addon, your emails even saved in eml
are not editable because of x-unsent missing & if x-unsent is missing & i deactivate lieser's addon,
i can finally open attachments with their exact name.
3) you haven't mentioned what i mentioned: opening attachments, you typed: "correctly displayed attachments",
the point is to open them, & then you see the nsmail..

**Comment by xlovinglyx** [comment]
& with subject or with destination or from source or without any of those, eml files should be saved too.
allowing users implementation of other names for a same body. those fields musn't depend on each
others.

**Comment by pgpgeek** [comment]
I've try on Thunderbird 74.x and  Thunderbird 84.x without any problem.
If you are using 2 plugins with the same goal, i can avoid the conflict of them.

My addon isn't the liesers  addon and i've already give answer about why implementation isn't possible you on your email (#ukrainianconsular@gmail.com).

I can provide some features with the possibility offered by the Webextension API, but i can't bypass their limitations.
I'm not working at Mozilla Fondation, i don't know if this limitations will be removed in the futur.

**Comment by xlovinglyx** [comment]
I'm waiting then..

& of course you could add lieser's code into your addon because lieser has updated his addon for webextention & the latest
thunderbird versions. and as i told you, lieser's addon is conflicting & not allowing attachment files to open. and as long as you don't include lieser's method to open eml's from windows folders, there will always be issues between the two addons. & one doesn't function without the other in terms of goals & today, conflict.

"If you are using 2 plugins with the same goal, i can avoid the conflict of them."

yes, because i'm forced to do so. look at it then cause the issue is still there.

again, liesers allows edition of emls because it has the X-Unsent support saved,
while your addon doesn't save X-unsent tag.

which is why both addons are actually needed until you use his technique to open emails from windows folders.
so now, to fix the attachments issue, you have to still look at lieser's addon & why it arrives.

as i told you already, one addon doesn't go without the other, which is your choice.
& lieser's deaf & refuses updates, & only maintains stupid transitions when the addon dies
& fixes it, begging him........ .

**Comment by xlovinglyx** [comment]
"If you are using 2 plugins with the same goal, i can avoid the conflict of them."
 Still unreviewed.

& i've found even better, subjects aren't saved, & i've been editing some recent emls, losing the subjects.
But in that case, i can't confirm if lieser's addon is responsible or not.

**Comment by pgpgeek** [comment]
Hi,

Because you're using this 2 plugins togethers, why doesn't have you ask lieser about your question?

Mine addon use WebExtension format with official WebExtension API like "browser.something.method", and Lieser not.
I don't have the time to understand how does it, and if his method will be persist in the time.
Your technicals recommendations about using the code of lieser isn't of your jurisdiction execepted if you understand what this technically implies.

 And to finish not have the time to be 24/24 and 7/7 on a "Free Time" because:
- Have a family life;)
- Have a job

Many tests have been done on more than 100 files with or without attachments, in rich text, in raw text, with or without subject, recipient, with multiple recipient ... 

To make a better contrôl of your bugs, i need something like details other than "doesn't work" :
- Recipient, Subject, attachments, ... empty of personnals datas.

**Comment by xlovinglyx** [comment]
Hi,

"Because you're using this 2 plugins togethers, why doesn't have you ask lieser about your question?"

because you refuse to implement lieser's webextention code into your eml editor, i'm forced to use 2
plugins, & i already & keep telling you that lieser doesn't do updates, but only fixes when begged,
his addon. & lieser has nothing to do with your addon, so i don't have to ask him about your addon.

"Mine addon use WebExtension format with official WebExtension API like "browser.something.method", and Lieser not.
I don't have the time to understand how does it, and if his method will be persist in the time."

another reason why i have to use 2 addons. 

"Your technicals recommendations about using the code of lieser isn't of your jurisdiction execepted if you understand what this technically implies."

Lieser learned Computer Coding, you think his approach belongs to him or he invented his technic ? legally or not,
his approach can be used by any other coder. But you don't wanna do it, so we're fixed.

"And to finish not have the time to be 24/24 and 7/7 on a "Free Time" because:

    Have a family life;)
    Have a job"

I was just following your initial "cadence", "rythm", then i'll wait.

"To make a better contrôl of your bugs, i need something like details other than "doesn't work" :

    Recipient, Subject, attachments, ... empty of personnals datas."

I already told you all this was tested, & that if i use lieser's addon, i get the attachment bug.
& i was waiting this:

"If you are using 2 plugins with the same goal, i can avoid the conflict of them."

& now, subjects aren't saved either.

**Comment by xlovinglyx** [comment]
As for the subject issue, it's not saved because you've made emls save if there's an email available in "To",
while i need to be able to save either the subject, either the from, either the to fields, together or not together.

**Comment by xlovinglyx** [comment]
As for the subject issue, it's not saved because there's no email available in "To",
& i often don't want to save "To" fields. I need to be able to save either the subject, 
either the from, either the to fields, together or not together.

**Comment by xlovinglyx** [comment]
I don't know if that helps:

"MailExtensions: menus API enabled in messages being composed"

in the latest tb release.

**Comment by xlovinglyx** [comment]
It's been almost a month, i've had no news, i hope you haven't forgotten this
"If you are using 2 plugins with the same goal, i can avoid the conflict of them."

**Comment by xlovinglyx** [comment]
Also, i disabled x-unsent support addon,
and your addon still doesn't save x-unsent,
& still doesn't save subjects either when i don't specify a "to" email

**Comment by xlovinglyx** [comment]
You were right & wrong,

I had to use what "i don't want" since the beginning, to realize attachment names are not broken 
while opening them & i could save any filed from sender to to & subject.

So yes, it all works besides priority field, IF.. i use "EML-EDITOR" button .. . which bypasses lieser's addon,
that allows me to open emls from the desktop.

It's funny cause lieser ignores my request of saving emls,
& you ignore my request of opening emls from desktop .. .

If only you could allow tb to open emls from the desktop,
that would fix a major issue & i would then dump lieser's
addon. But like i told you, i cannot use a button to open
eml's.. because of the way folders and icons are displayed
on explorer, something i can't control with a tb's button .. .

I can also open various folders on the desktop, while i can only
open one folder & not placed the same way as explorer allows
me to place them.

Opening emls on an explorer based click is important, i cannot sit on that.
an error you did since the beginning & that lieser integrated since the beginning.

i'm sure u can make ur addon open files from explorer, pleaaase do an effort, 
this is driving me nuts. like that i'll dump liesers x-unsent crap support addon,
from more than a decade of needless hopes.

I also found out with lieser's addon, i save through drafts which destroys the fonttype size,
& this doesn't happen with your saving button.

please make it open from desktop
